// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNfvjFZciLCeUYQ6OknIFtAZS49yh4JxA',
    appId: '1:831040074699:web:402a3acc11617152c93c4e',
    messagingSenderId: '831040074699',
    projectId: 'lawcase-83ac4',
    authDomain: 'lawcase-83ac4.firebaseapp.com',
    storageBucket: 'lawcase-83ac4.firebasestorage.app',
    measurementId: 'G-690KQ63HSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLq9SlzgnMeLv62sJm5tNQ-vyLj80EkCA',
    appId: '1:831040074699:android:fe707c97bc0c818ec93c4e',
    messagingSenderId: '831040074699',
    projectId: 'lawcase-83ac4',
    storageBucket: 'lawcase-83ac4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDItQ7ZjwYgdvZGo-KJHE2qA6uXkpf9xYw',
    appId: '1:831040074699:ios:740a7c83eb5a85aac93c4e',
    messagingSenderId: '831040074699',
    projectId: 'lawcase-83ac4',
    storageBucket: 'lawcase-83ac4.firebasestorage.app',
    iosClientId: '831040074699-ve2p56odu95injgeu5enegu82rtvqhjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.legalCase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDItQ7ZjwYgdvZGo-KJHE2qA6uXkpf9xYw',
    appId: '1:831040074699:ios:740a7c83eb5a85aac93c4e',
    messagingSenderId: '831040074699',
    projectId: 'lawcase-83ac4',
    storageBucket: 'lawcase-83ac4.firebasestorage.app',
    iosClientId: '831040074699-ve2p56odu95injgeu5enegu82rtvqhjt.apps.googleusercontent.com',
    iosBundleId: 'com.example.legalCase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNfvjFZciLCeUYQ6OknIFtAZS49yh4JxA',
    appId: '1:831040074699:web:29934e7fd6f2dd31c93c4e',
    messagingSenderId: '831040074699',
    projectId: 'lawcase-83ac4',
    authDomain: 'lawcase-83ac4.firebaseapp.com',
    storageBucket: 'lawcase-83ac4.firebasestorage.app',
    measurementId: 'G-XM2X157P42',
  );
}
